import {
    LayoutDashboard,
    ShoppingBag,
    FolderTree,
    Settings,
    Users,
    PackageSearch,
    Truck,
    ClipboardList,
    Mail,
    Star,
    BarChart3,
    DollarSign,
    TrendingUp,
    RotateCcw,
    ShoppingCart,
    Tag,
    Receipt,
    Archive,
    History,
    Store,
    Image,
    AlertTriangle,
    Sparkles,
    Gift,
    Award,
    MessageSquare,
    Package,
    Timer,
    Percent,
    Clock,
    Bell,
    UserCheck,
    MapPin,
    Activity,
    Megaphone,
} from "lucide-react"

export interface SidebarItem {
    title: string
    href: string
    icon: any
}

export const adminConfig = {
    navItems: [
        { title: "Dashboard", href: "/admin", icon: LayoutDashboard },
        { title: "Orders", href: "/admin/orders", icon: ClipboardList },
        { title: "Inventory", href: "/admin/inventory", icon: PackageSearch },
        { title: "Pricing", href: "/admin/pricing", icon: TrendingUp },
        { title: "Products", href: "/admin/products", icon: ShoppingBag },
        { title: "Live Carts", href: "/admin/live-carts", icon: ShoppingCart },
        { title: "Customers", href: "/admin/customers", icon: UserCheck },
        { title: "Back in Stock", href: "/admin/inventory/demand", icon: Bell },
        // { title: "Stock", href: "/admin/stock", icon: Archive },
        { title: "Return Requests", href: "/admin/return-requests", icon: RotateCcw },
        { title: "Concerns", href: "/admin/concerns", icon: AlertTriangle },

        // { title: "Abandoned Carts", href: "/admin/abandoned-carts", icon: Timer },
        { title: "Categories", href: "/admin/categories", icon: FolderTree },
        { title: "Tags", href: "/admin/tags", icon: Tag },
        { title: "Promos", href: "/admin/promos", icon: Tag },
        { title: "Flash Sales", href: "/admin/flash-sales", icon: Clock },
        { title: "Free Gifts", href: "/admin/free-gifts", icon: Gift },
        { title: "Gift Products", href: "/admin/gift-products", icon: Package },
        { title: "Buy X Get Y", href: "/admin/bxgy", icon: Percent },
        { title: "Hero Banners", href: "/admin/hero-banners", icon: Image },
        // { title: "Showcase", href: "/admin/showcase", icon: Sparkles },
        { title: "Broadcast", href: "/admin/broadcast", icon: Megaphone },

        { title: "Messages", href: "/admin/messages", icon: Mail },
        { title: "Reviews", href: "/admin/reviews", icon: Star },

        { title: "Rewards", href: "/admin/rewards", icon: Award },
        { title: "Reward Users", href: "/admin/rewards/users", icon: Users },
        { title: "Revenue Report", href: "/admin/reports/revenue", icon: DollarSign },
        { title: "Sales Report", href: "/admin/reports/sales", icon: BarChart3 },
        { title: "Purchase", href: "/admin/purchase", icon: Receipt },
        { title: "Purchase History", href: "/admin/purchase/list", icon: History },
        { title: "Shipping", href: "/admin/shipping", icon: MapPin },
        { title: "Delivery Partners", href: "/admin/delivery-partners", icon: Truck },
        { title: "Visitor History", href: "/admin/visitor-history", icon: Activity },
        { title: "Wholesale", href: "/admin/wholesale", icon: Store },
        { title: "WhatsApp", href: "/admin/whatsapp", icon: MessageSquare },
        { title: "Legal Settings", href: "/admin/settings/legal", icon: Settings },
    ] as SidebarItem[],
}
